/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our samples at https://docs.gradle.org/7.4.2/samples
 */
 plugins {
    id("org.openapi.generator") version "6.2.1"
 }

openApiGenerate {
    generatorName.set("typescript-fetch")
    inputSpec.set("$projectDir/src/main/resources/api.yaml")
    outputDir.set("$buildDir/generated/typescript")
    configOptions.putAll(mapOf(
        "npmName" to "@vultureweb/fetch-demo",
        "supportES6" to "true"
    ))
}

 

