import org.openapitools.generator.gradle.plugin.tasks.GenerateTask

/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our samples at https://docs.gradle.org/7.4.2/samples
 */
 plugins {
    id("org.openapi.generator") version "6.2.1"
 }

tasks.register<GenerateTask>("typescript") {
    generatorName.set("typescript-fetch")
    inputSpec.set("$projectDir/src/main/resources/api.yaml")
    outputDir.set("$buildDir/generated/typescript")
    configOptions.putAll(mapOf(
        "npmName" to "@vultureweb/fetch-demo",
        "supportES6" to "true"
    ))
}

tasks.register<GenerateTask>("jaxrs") {
    generatorName.set("jaxrs-spec")
    inputSpec.set("$projectDir/src/main/resources/api.yaml")
    templateDir.set("$projectDir/src/main/resources/template")
    outputDir.set("$buildDir/generated/jaxrs")
    configOptions.putAll(mapOf(
        "apiPackage" to "dev.vultureweb.api.greet",
        "modelPackage" to "dev.vultureweb.api.greet.model",
        "groupId" to "dev.vultueweb.api",
        "artifactId" to "greet",
        "artifactVersion" to "1.0.0",
        "booleanGetterPrefix" to "is",
        "dateLibrary" to "java8",
        "generateBuilders" to "true",
        "hideGenerationTimestamp" to "true",
        "interfaceOnly" to "true",
        "useBeanValidation" to "true",
        "useSwaggerAnnotations" to "false",
        "jackson" to "false"
    ))
}


 

