openapi: 3.0.3
info:
  title: My service
  description: My service
  version: 1.0.0
servers:
  - url: 'https://api.vultureweb.dev'

paths:
  /hello:
    get:
      description: Simple hello endpoint
      operationId: hello
      responses:
        "200":
          description: Return a greeting
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Greeting"
        "204":
          description: default response
  /hello/{name}:
    get:
      description: Say hello to a specific person
      operationId: hello-name
      parameters:
        - in: path
          name: name
          description: Name of the persone to greet
          schema:
            type: string
          required: true
      responses:
        "200":
          description: Return a greeting
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Greeting"
        "204":
          description: default response


components:
  schemas:
    Greeting:
      required: [message]
      properties:
        message:
          type: string
        time:
          type: string
          format: date
        important:
          type: boolean
          default: true